version: '3'

services:
###> doctrine/doctrine-bundle ###
  symfonyospocDB:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  symfonyospocMAIL:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###
